<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Fonts\Constantia.ttf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Fonts\Constantia.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microcharts" Version="0.9.5.9" />
    <PackageReference Include="Microcharts.Forms" Version="0.9.5.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.32" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.32" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.32">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="QuestPDF" Version="2023.9.0" />
    <PackageReference Include="Spire.Email" Version="6.5.7" />
    <PackageReference Include="Xam.Plugins.Messaging" Version="5.2.0" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2612" />  
    <PackageReference Include="Xamarin.Essentials" Version="1.8.0" />  
    <PackageReference Include="Xamarin.Forms.DataGrid" Version="5.0.0.2545" />  
    <PackageReference Include="Xamarin.Plugin.Calendar" Version="2.0.9699" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\ListToAdd\AddInscriptionPage.xaml.cs">
      <DependentUpon>AddInscriptionPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\ListToAdd\AddNoticePage.xaml.cs">
      <DependentUpon>AddNoticePage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Main3Days\TodayPage.xaml.cs">
      <DependentUpon>TodayPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Main3Days\TomorrowPage.xaml.cs">
      <DependentUpon>TomorrowPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Main3Days\YesterdayPage.xaml.cs">
      <DependentUpon>YesterdayPage.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Views\ListToAdd\AddBudgetPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToAdd\AddNoticePage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToAdd\AddQuestPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToAdd\AddInscriptionPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToGO\Budget\BudgetPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToGO\Budget\BudgetSettingsPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToGO\Calendar\CalendarPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToGO\Habits\HabitsPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToGO\Habits\HabitsSettingsPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToGO\Habits\NewHabitPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToGO\Language\English\EnglishListWordsPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToGO\Language\English\EnglishMainPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToGO\Language\English\EnglishNewWordPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToGO\Language\English\EnglishSettingsPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToGO\Language\English\EnglishTestPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToGO\Notice\NoticePage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToGO\Notice\NoticeSettingsPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToGO\Notice\NoticeSpecifyPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\ListToGO\Raports\RaportMainPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Main3Days\TodayPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Main3Days\TomorrowPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Main3Days\YesterdayPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\TestowyPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>